PolicyEngine/policyengine-us-data

Dockerfile
docker/build_and_publish.Dockerfile
docker/docs.Dockerfile
docs/Dockerfile
setup.py

Adds Dockerfiles for docs and publishing so we can run these from GCP.

Add dockerfiles

---

docs/download_prerequisites.py
setup.py

Also testing if the PR action works.

Format files

---

docs/pages/Benchmarks.py
policyengine_us_data/utils/github.py

Fix broken GitHub upload

---

MANIFEST.in
setup.py

fix: Add MANIFEST.in

---

.github/workflows/ci_cd.yaml

Fixes #17. Breaks PyPI publishing out of updating CI/CD actions job and adds to beginning of action.

Rearrange CI/CD script

---

pyproject.toml

Add build to dependencies

---

pyproject.toml

Prevent setuptools_scm from using local version numbers

---

policyengine_us_data/datasets/__init__.py

Add CPS_2024 and EnhancedCPS_2024 to `DATASETS`

---

.github/workflows/ci_cd.yaml
CHANGELOG.md
changelog.yaml
changelog_entry.yaml
pyproject.toml

Fix CI/CD issues to allow for push to PyPI

---

CHANGELOG.md
changelog.yaml
changelog_entry.yaml
pyproject.toml

Lighten dependencies

---

.github/fetch_version.py
.github/workflows/ci_cd.yaml
changelog_entry.yaml

Fixes #51. The aim with this PR is to develop a system that can then be applied to other repositories when migrating to `pyproject.toml`.

Fix version checking

---

.github/workflows/ci_cd.yaml
.github/workflows/pull_request.yaml
.github/workflows/push.yaml
changelog_entry.yaml

Determine why sequenced update not working

---

.github/workflows/pull_request.yaml
.github/workflows/push_1.yaml
.github/workflows/push_2.yaml
changelog_entry.yaml

Fix changelogging

---

changelog_entry.yaml
policyengine_us_data/datasets/cps/cps.py
policyengine_us_data/datasets/cps/enhanced_cps.py
policyengine_us_data/utils/loss.py

Add State and household size as rent predictors

---

.github/workflows/pull_request.yaml
.github/workflows/push.yaml
Makefile
changelog_entry.yaml
policyengine_us_data/storage/download_private_prerequisites.py
policyengine_us_data/storage/upload_completed_datasets.py
policyengine_us_data/utils/huggingface.py

Automatically calibrate weights

---

Makefile
changelog_entry.yaml
pyproject.toml

Modify install details to prevent circular deps

---

.github/workflows/pull_request.yaml
.github/workflows/push.yaml
changelog_entry.yaml

Increase memory limit in actions

---

changelog_entry.yaml
policyengine_us_data/datasets/cps/extended_cps.py

Add interest expense

---

.github/workflows/code_changes.yaml
changelog_entry.yaml
policyengine_us_data/datasets/cps/extended_cps.py
policyengine_us_data/tests/test_datasets/test_enhanced_cps.py

Reinstate larger runner for data deployment

---

.github/workflows/code_changes.yaml
.github/workflows/pr_code_changes.yaml

Datasets are not being uploaded to Hugging Face

---

policyengine_us_data/datasets/cps/census_cps.py
policyengine_us_data/datasets/cps/cps.py

Add ESI data from CPS

---

policyengine_us_data/tests/test_datasets/test_enhanced_cps.py

Increase the tolerance for the JCT tax expenditure targets to 30%

---

.github/workflows/pr_code_changes.yaml
changelog_entry.yaml
policyengine_us_data/datasets/cps/cps.py
policyengine_us_data/datasets/cps/enhanced_cps.py
policyengine_us_data/datasets/cps/extended_cps.py
policyengine_us_data/datasets/puf/puf.py
policyengine_us_data/datasets/sipp/sipp.py

Run lite versions of imputations and calibrations in tests

---

policyengine_us_data/datasets/cps/census_cps.py
policyengine_us_data/datasets/cps/cps.py
policyengine_us_data/tests/test_datasets/test_cps.py

Overtime occupation variable

---

changelog_entry.yaml
policyengine_us_data/datasets/cps/cps.py
policyengine_us_data/tests/test_datasets/test_cps.py
pyproject.toml

Adding auto loan balance

---

changelog_entry.yaml
policyengine_us_data/datasets/cps/census_cps.py
policyengine_us_data/datasets/cps/cps.py

Added hours_worked_last_week to CPS

---

changelog_entry.yaml
policyengine_us_data/utils/data_upload.py

Data upload is missing HF token

---

policyengine_us_data/datasets/cps/cps.py

- allow per-variable probabilities when simulating QBI qualification flags
- `pytest -q` *(fails: ModuleNotFoundError: No module named 'policyengine_core')*

Add QBI qualification probabilities

---

.github/workflows/code_changes.yaml

fixes #278
- fix comment to reflect post-merge usage
- make `HUGGING_FACE_TOKEN` available for all steps
- simplify environment configuration in post-merge workflow

Fix post merge workflow

---

changelog_entry.yaml
policyengine_us_data/datasets/cps/cps.py
policyengine_us_data/tests/test_datasets/test_cps.py
policyengine_us_data/tests/test_datasets/test_enhanced_cps.py

Add take-up flags for Medicaid and ACA PTC

---

changelog_entry.yaml
policyengine_us_data/datasets/cps/cps.py

Adjust takeup variables

---

CHANGELOG.md
changelog.yaml
changelog_entry.yaml
policyengine_us_data/datasets/cps/cps.py
policyengine_us_data/datasets/cps/enhanced_cps.py
policyengine_us_data/utils/loss.py
pyproject.toml

Add real estate taxes targets by state

---

changelog_entry.yaml
policyengine_us_data/datasets/cps/cps.py
policyengine_us_data/datasets/cps/enhanced_cps.py
policyengine_us_data/datasets/cps/extended_cps.py
policyengine_us_data/datasets/puf/puf.py
policyengine_us_data/datasets/sipp/sipp.py

Reduce differences in production and PR test builds

---

changelog_entry.yaml
policyengine_us_data/datasets/cps/cps.py
policyengine_us_data/utils/soi.py

Use "SURVIVING_SPOUSE" instead of "WIDOW" in `soi.py`

---

changelog_entry.yaml
pyproject.toml

Pin -us at a version before OBBBA was converted to the baseline
